### ISSUE TITLE
Feature Request: Sort Spidertron Logistics Requests

### ISSUE THREAD

**Issue by scotthmccoy** [tfg13/factorio_logistics_requests_sorted#3]
See title. 🕷🤖

**Comment by tfg13** [comment]
This looks like it should be possible, I'll give it a try. No promises when, thought, busy days :)

**Comment by tfg13** [comment]
Done, I just released version 1.1.0, which will also sort spiderton

**Comment by scotthmccoy** [comment]
Thank you!!!
