### ISSUE TITLE
Mod does not sort on load of a game that was not started with this mod. 

### ISSUE THREAD

**Issue by frigonj** [tfg13/factorio_logistics_requests_sorted#5]
If you install this mod on an existing save, add an item tot he logistics list, and then the mod should work as intended.

**Comment by tfg13** [comment]
Yeah this is not ideal. It is like this for 3 reasons:

- It is the easiest to implement :P
- It is a one-time problem
- This actually helps if enabling the mod late in a multiplayer game - players with a nice hand-crafted ordering get a chance to disable the sorting in the settings before it messes up everything. Granted, this is not a super important use case.

**Comment by tfg13** [comment]
But this is still a good point, I should probably put a note about the fact that you have to touch your inventory once in the mod description.

**Comment by tfg13** [comment]
Done in 2ef5cd00a26722606950fc69c177d58b6462e6ab
