### ISSUE TITLE
Feature request: Key and/or button to toggle on and off.

### ISSUE THREAD

**Issue by DeadlyDad** [tfg13/factorio_logistics_requests_sorted#7]
While I *LOVE* this mod, it does interfere somewhat with the use of the '[Logistic Request Manager (continued)](https://mods.factorio.com/mod/LogisticRequestManager)'.  That mod allows easily adding in requests for specific circumstances.  For example, you can pass it an entire blueprint and it will queue up logistics requests for every entity within the blueprint.  (As you can imagine, that is *INCREDIBLY* handy.)  After you are done placing the blueprint/etc., you probably want to remove those (temporary) requests, but, if they automatically get sorted by LRS, then you have to look through all the rest of the requests to find them.  It would be *MUCH* better if you could toggle sorting off for these temporary requests, and then toggle it back on after you are done placing blueprints/etc.

Does that sound reasonable?

**Comment by tfg13** [comment]
Hey there, sorry for the late reply. I can take a look at this, it shouldn't be super hard.

In a way this is already possible in the mod settings - but that one is very annoying to reach in game for quick changes.

FWIW I am actually surprised LRM doesn't have this option on its own, I always assumed people either just want a little bit of sorting and use this mod, or go all in on request customization and use LRM and friends.

**Comment by tfg13** [comment]
Just released version 1.2 with a quickbar shortcut toggle. Also has an optional hotkey, but without a default
