### ISSUE TITLE
Support for version 2.0

### ISSUE THREAD

**Issue by pindab0ter** [tfg13/factorio_logistics_requests_sorted#9]
Factorio 2.0 is out. Is there any word on when support will be added? I'm looking forward to being able to use this amazing QoL mod again!

**Comment by a7x492** [comment]
Or please just let us know if you don't think you'll have to update this soon, and maybe I can try to reupload this. Thanks!

**Comment by pindab0ter** [comment]
I forked this mod, updated, and reuploaded it:

Source: https://github.com/pindab0ter/sorted-logistic-sections
Mod: https://mods.factorio.com/mod/sorted-logistic-sections

**Comment by tfg13** [comment]
Thanks! I was going to do it eventually, but I wanted to finish my vanilla run first, which is taking much longer than I thought :D

**Comment by pindab0ter** [comment]
Hah, wait till you start doing the Space Age stuff!

If you're interested, feel free to browse through the code. As signal filters can now be in logistic sections, `inventory.sort_and_merge()` is no longer an option. I think you might find my solution to that problem interesting!
